java_test(
    name = "ConsumerTest",
    srcs = ["ConsumerTest.java"],
    deps = [
        "//src/main/java/com/myproject/consumer",
        "//src/main/java/com/myproject/producer",
         "@maven//:junit_junit"
    ],
)